services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER: THECREW
      - POSTGRES_PASSWORD: postgrespw
    ports:
      - 5433:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  data:

